In [1]:
import pandas as pd
import openpyxl
import matplotlib.pyplot as plt

In [2]:
usage_data = pd.read_excel("input data\\Safety Stock Çalışma.xlsx",sheet_name="USAGE")
lead_time_data = pd.read_excel("input data\\Safety Stock Çalışma.xlsx",sheet_name="DATA")

In [3]:
df = usage_data.transpose() # After transpose: Rows: Time, Columns: Raw Material Data
df = df.rename(columns=df.iloc[0]).drop(df.index[0])
df = df.dropna()

df[df.columns[:]] = df[df.columns[:]].apply(pd.to_numeric) # columns to numeric

clean_df = df.loc[:, (df != 0).any(axis=0)] #Remove raw materials with all 0 values (Kullanılmayalan RM ler)

In [4]:
clean_df.index = pd.to_datetime(clean_df.index ) #Datetime the index
clean_df = clean_df.loc[(df!=0).any(axis=1)] # Remove holiday data, where all rm usage is 0 
RM_list = clean_df.columns.copy() # RM names, all 0 RMs removed, (118 Raw materials)
clean_df #330 days 118 RMs

,RM0001,RM0002,RM0003,RM0005,RM0006,RM0007,RM0009,RM0012,RM0013,RM0015,...,RM0158,RM0159,RM0160,RM0162,RM0163,RM0164,RM0165,RM0166,RM0168,RM0172
2022-03-14,521.447720,49.313152,368.502844,460.394816,194.001963,4.638129,7663.130065,3912.605646,16279.963682,218.331260,...,550.837161,4936.798071,0.000000,438.385255,2010.046860,320.036845,216.436171,1141.355956,1073.079161,50.985645
2022-03-15,500.796325,47.848405,391.534272,433.575700,190.306687,4.545366,7969.655267,3950.592108,16446.085760,216.103390,...,556.345533,5404.494730,0.000000,447.066151,1989.324728,310.623997,234.662375,1189.413049,1105.271536,48.436363
2022-03-16,531.773417,46.383658,376.179986,469.334521,175.525585,4.730892,7739.761365,3646.700408,17276.696152,213.875520,...,534.312046,5248.595844,0.000000,425.363910,2072.213258,323.174461,218.714446,1249.484415,1116.002328,51.495502
2022-03-17,542.099115,48.824903,403.049985,451.455111,182.916136,4.452604,7279.973561,3722.673333,16279.963682,216.103390,...,528.803675,5300.562139,0.000000,438.385255,2051.491125,301.211148,223.270997,1153.370230,1126.733119,48.436363
2022-03-18,505.959174,48.824903,395.372843,424.635995,182.916136,4.545366,7663.130065,3950.592108,15947.719525,211.647650,...,561.853905,5404.494730,0.000000,438.385255,2175.823921,313.761613,239.218926,1201.427323,1126.733119,53.025071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-11,659.143937,423.781044,160.839171,210.402728,249.422378,1.480982,11100.572673,4369.583216,17717.426646,227.213712,...,564.186231,0.000000,5549.617884,512.785368,2165.930898,306.353275,123.903933,1327.280163,1104.421375,51.952167
2023-02-12,633.546114,463.928722,148.584758,192.368208,246.928154,1.495646,10149.095015,4069.709858,17370.026124,220.464790,...,592.680485,0.000000,5439.724461,523.580850,1978.494570,309.447752,123.903933,1409.379967,1149.499798,51.952167
2023-02-13,646.345026,437.163603,150.116560,194.372044,261.893497,1.451656,10360.534494,4198.227012,17543.726385,224.964072,...,547.089678,0.000000,5219.937614,550.569553,2040.973346,303.258797,115.643671,1368.330065,1126.960586,51.952167
2023-02-14,627.146659,428.241897,160.839171,198.379715,254.410825,1.510309,10571.973974,4112.548909,16848.925340,213.715868,...,558.487380,0.000000,5219.937614,555.967294,1978.494570,300.164320,112.103559,1395.696666,1183.308616,49.454466
2023-02-15,627.146659,428.241897,150.116560,194.372044,239.445483,1.510309,10360.534494,4069.709858,18064.827169,224.964072,...,541.390827,0.000000,5714.458020,512.785368,1978.494570,293.975365,122.723896,1409.379967,1093.151769,51.952167

In [5]:
clean_df['month'] = clean_df.index.month
clean_df['week'] = clean_df.index.week # Get week of days in data
clean_df['year'] = clean_df.index.year # Get year of days in data

#grouped_by_week_averages = clean_df.groupby(['week','year']).mean() #Weekly averages 
grouped_by_month_sum = clean_df.groupby(['month','year']).sum() # Monthly usage
grouped_by_month_sum

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)

,,RM0001,RM0002,RM0003,RM0005,RM0006,RM0007,RM0009,RM0012,RM0013,RM0015,...,RM0159,RM0160,RM0162,RM0163,RM0164,RM0165,RM0166,RM0168,RM0172,week
month,year,,,,,,,,,,,,,,,,,,,,,
1,2023,19136.932326,13193.419112,4588.971319,6013.510350,7472.694440,44.285773,315827.150498,127788.889551,521899.804915,6704.379264,...,0.000000,163345.584620,16193.222150,61795.674613,9185.647084,3511.791479,40625.719634,33391.842173,1484.333350,80
2,2023,9637.580285,6597.601727,2273.193617,2993.730244,3733.852996,22.112094,158262.450390,63530.312841,261071.492640,3349.715027,...,0.000000,81815.653761,8107.406556,31031.125362,4641.716287,1770.056189,20593.367480,17141.070518,752.307338,88
3,2022,9236.336342,875.918764,7009.231176,8099.372876,3327.595573,82.280409,137246.659455,68451.605570,302009.938508,3965.608600,...,41573.036387,52485.958439,7804.125620,37279.116513,5657.121881,4110.008973,21301.306429,19497.848361,928.448598,213
4,2022,15327.024821,5584.968000,8627.885275,11501.231335,5947.627796,144.468039,246107.914620,110201.710903,489266.262865,6469.437431,...,0.000000,156673.788585,13119.864590,61208.845982,9633.294928,6711.551464,37271.229860,32480.631030,559.686373,456
5,2022,15346.238753,10647.790509,4479.662002,7627.310476,6049.419166,118.705050,221861.473211,100232.278132,447914.122243,6645.417943,...,0.000000,139022.749402,10491.881747,52489.464104,8378.734725,2887.083168,32846.036283,27793.360395,486.564252,536
6,2022,17269.255952,12180.886598,5337.563450,9562.215213,6989.777040,151.015267,273453.277925,113850.716943,521446.907592,6734.851010,...,0.000000,159702.926940,13323.051843,61298.602038,10163.642866,3418.455948,38729.999383,32278.155228,1569.906464,718
7,2022,16289.541909,11419.239803,4228.742970,6641.414299,6389.067725,76.448505,252401.273661,108015.394625,469484.652349,6918.766666,...,0.000000,141952.847487,12420.721136,55075.474981,8365.232586,3009.019010,35569.375991,28769.034625,473.950779,766
8,2022,19730.598757,13518.945446,5258.699144,8335.252115,7618.203130,98.429483,300844.589272,130106.022919,548131.417558,6698.702023,...,0.000000,170587.603558,14934.610876,65007.432831,10020.214285,3599.548205,41495.587370,34357.071815,577.779559,1015
9,2022,18768.102340,13317.185288,5046.550549,7923.796899,7389.176037,98.658780,286378.206165,125279.292468,535485.967354,6665.787040,...,0.000000,165832.675728,14843.250023,63171.745551,9647.725941,3473.943356,40570.741915,33249.029233,1557.744425,1112
10,2022,19464.208035,13667.524550,4592.056227,6126.439703,7594.550814,48.851164,299687.721346,129910.639541,529318.721691,6674.985987,...,0.000000,167065.283265,15294.456653,63172.534605,9428.102775,3640.188000,40752.308019,34061.147924,521.291169,1284
11,2022,18856.801773,13189.094948,4607.037961,5998.352692,7493.873156,45.847122,282242.954802,125697.259542,512870.519000,6679.154260,...,0.000000,160689.945197,15194.282838,60871.547864,9145.130008,3521.134660,38640.629029,32858.767960,510.138608,1374
12,2022,19551.617056,13538.243056,4694.359271,6188.845957,7596.906785,45.213953,325141.059569,132394.087548,525947.021002,6909.321533,...,0.000000,170153.482203,16609.927733,64290.660397,9499.736552,3608.908562,42102.147774,34509.787074,1538.483493,1554

In [6]:
grouped_by_month_sum.reset_index()
grouped_by_month_sum = grouped_by_month_sum.sort_values(['year','month'],ascending=[True,True])
grouped_by_month_sum.drop('week',inplace = True,axis=1)
grouped_by_month_sum

,,RM0001,RM0002,RM0003,RM0005,RM0006,RM0007,RM0009,RM0012,RM0013,RM0015,...,RM0158,RM0159,RM0160,RM0162,RM0163,RM0164,RM0165,RM0166,RM0168,RM0172
month,year,,,,,,,,,,,,,,,,,,,,,
3,2022,9236.336342,875.918764,7009.231176,8099.372876,3327.595573,82.280409,137246.659455,68451.605570,302009.938508,3965.608600,...,9948.119133,41573.036387,52485.958439,7804.125620,37279.116513,5657.121881,4110.008973,21301.306429,19497.848361,928.448598
4,2022,15327.024821,5584.968000,8627.885275,11501.231335,5947.627796,144.468039,246107.914620,110201.710903,489266.262865,6469.437431,...,15933.268577,0.000000,156673.788585,13119.864590,61208.845982,9633.294928,6711.551464,37271.229860,32480.631030,559.686373
5,2022,15346.238753,10647.790509,4479.662002,7627.310476,6049.419166,118.705050,221861.473211,100232.278132,447914.122243,6645.417943,...,13347.776698,0.000000,139022.749402,10491.881747,52489.464104,8378.734725,2887.083168,32846.036283,27793.360395,486.564252
6,2022,17269.255952,12180.886598,5337.563450,9562.215213,6989.777040,151.015267,273453.277925,113850.716943,521446.907592,6734.851010,...,15729.600780,0.000000,159702.926940,13323.051843,61298.602038,10163.642866,3418.455948,38729.999383,32278.155228,1569.906464
7,2022,16289.541909,11419.239803,4228.742970,6641.414299,6389.067725,76.448505,252401.273661,108015.394625,469484.652349,6918.766666,...,14556.683162,0.000000,141952.847487,12420.721136,55075.474981,8365.232586,3009.019010,35569.375991,28769.034625,473.950779
8,2022,19730.598757,13518.945446,5258.699144,8335.252115,7618.203130,98.429483,300844.589272,130106.022919,548131.417558,6698.702023,...,17179.777020,0.000000,170587.603558,14934.610876,65007.432831,10020.214285,3599.548205,41495.587370,34357.071815,577.779559
9,2022,18768.102340,13317.185288,5046.550549,7923.796899,7389.176037,98.658780,286378.206165,125279.292468,535485.967354,6665.787040,...,17021.887239,0.000000,165832.675728,14843.250023,63171.745551,9647.725941,3473.943356,40570.741915,33249.029233,1557.744425
10,2022,19464.208035,13667.524550,4592.056227,6126.439703,7594.550814,48.851164,299687.721346,129910.639541,529318.721691,6674.985987,...,17118.588224,0.000000,167065.283265,15294.456653,63172.534605,9428.102775,3640.188000,40752.308019,34061.147924,521.291169
11,2022,18856.801773,13189.094948,4607.037961,5998.352692,7493.873156,45.847122,282242.954802,125697.259542,512870.519000,6679.154260,...,16873.093877,0.000000,160689.945197,15194.282838,60871.547864,9145.130008,3521.134660,38640.629029,32858.767960,510.138608
12,2022,19551.617056,13538.243056,4694.359271,6188.845957,7596.906785,45.213953,325141.059569,132394.087548,525947.021002,6909.321533,...,17568.417290,0.000000,170153.482203,16609.927733,64290.660397,9499.736552,3608.908562,42102.147774,34509.787074,1538.483493
1,2023,19136.932326,13193.419112,4588.971319,6013.510350,7472.694440,44.285773,315827.150498,127788.889551,521899.804915,6704.379264,...,17085.154741,0.000000,163345.584620,16193.222150,61795.674613,9185.647084,3511.791479,40625.719634,33391.842173,1484.333350
2,2023,9637.580285,6597.601727,2273.193617,2993.730244,3733.852996,22.112094,158262.450390,63530.312841,261071.492640,3349.715027,...,8468.492310,0.000000,81815.653761,8107.406556,31031.125362,4641.716287,1770.056189,20593.367480,17141.070518,752.307338

In [7]:
#new = pd.merge(clean_df,grouped_by_month_sum.reset_index(),on='month',how='left')
#new_ss = new[[x for x in new.columns if '_y' in x]]
#monthly_data_formatted_daily = new_ss.transpose()

In [10]:
grouped_by_month_std = clean_df.groupby(['month','year']).std() #Weekly standart deviations
z_score = 1.96
    
# Calculate monthly safety stock for each Raw Material
for rm_id in list(RM_list):
    lead_time = lead_time_data.loc[lead_time_data['MATERIAL NUMBER'] == rm_id, 'TRANSIT TIME'].iloc[0] 
    rm_data = grouped_by_month_std[rm_id]
    safety_stock_data =  rm_data * lead_time * z_score 

    if len(grouped_by_month_safety_stock) != 0:
        grouped_by_month_safety_stock[rm_id] = safety_stock_data
    else:
        grouped_by_month_safety_stock = safety_stock_data    
        grouped_by_month_safety_stock = pd.DataFrame(grouped_by_month_safety_stock)

In [13]:
grouped_by_month_safety_stock = grouped_by_month_safety_stock.sort_values(['year','month'],ascending=[True,True])
grouped_by_month_safety_stock

,,RM0001,RM0002,RM0003,RM0005,RM0006,RM0007,RM0009,RM0012,RM0013,RM0015,...,RM0158,RM0159,RM0160,RM0162,RM0163,RM0164,RM0165,RM0166,RM0168,RM0172
month,year,,,,,,,,,,,,,,,,,,,,,
3,2022,406.252729,43.107950,163.798102,310.196515,135.362550,2.120509,5291.001271,2598.289826,9988.929731,85.474767,...,933.073087,15639.843211,63197.587110,357.972300,1480.881400,131.766182,542.586926,2419.446213,758.968662,31.825823
4,2022,356.174950,163.203849,131.486570,260.925531,161.807112,2.966047,6629.464669,3121.902136,11374.679940,116.888079,...,1068.022190,0.000000,3767.108674,401.494404,1778.633819,206.841222,426.152561,2531.369875,983.970861,13.455933
5,2022,815.763912,652.084778,131.368721,421.986490,320.889883,5.819844,12300.608604,6003.253692,22001.326087,234.291667,...,1948.549663,0.000000,8209.620277,694.020428,2859.242021,454.523987,429.924793,5037.022142,1501.963103,24.375620
6,2022,404.596648,370.417259,70.584800,224.134290,178.088587,3.677710,7691.027037,2650.096184,11141.188298,104.067004,...,1117.434773,0.000000,4034.910701,313.059709,1584.712623,247.231471,206.665969,3024.959939,1023.330928,35.421153
7,2022,721.713125,621.554017,87.771406,293.831302,238.730513,2.739219,9506.830868,4050.332645,18857.026937,204.214840,...,1913.554869,0.000000,5791.237972,717.280611,2641.768056,363.230748,359.404970,4230.574811,1373.823327,17.600564
8,2022,464.360401,382.866727,82.174579,182.394415,200.483704,2.375696,7206.104529,2641.443631,11834.549344,92.668138,...,1147.016243,0.000000,4165.682606,453.914400,1477.798894,233.484221,229.632494,2933.952780,1130.310828,14.913748
9,2022,447.822175,333.620997,79.917613,211.118370,182.747625,2.361763,7224.503911,2916.930919,11067.501070,126.763079,...,939.813307,0.000000,4214.418683,504.617361,1522.900697,258.793950,210.059551,2649.604051,1015.472411,38.742867
10,2022,476.845208,386.545888,63.081778,157.484232,194.382099,1.080998,7416.473433,2919.981666,10503.998203,103.919970,...,1136.970112,0.000000,4113.754312,473.483253,1515.992033,227.851346,236.749129,2645.913443,1107.366061,11.908477
11,2022,493.244299,404.535200,69.364831,128.101138,169.361802,0.890113,5852.035067,3170.110068,10448.840682,115.653665,...,974.030317,0.000000,4100.410080,394.420429,1595.755697,196.142785,190.177491,2794.643211,836.999260,9.686660
12,2022,1004.849794,813.392510,134.216001,277.626398,327.693623,1.767237,16936.933399,6747.336228,20790.095846,225.858746,...,2138.921501,0.000000,8001.907147,1072.041759,3156.227135,443.418218,471.473502,6278.594759,2131.087561,60.723837
1,2023,665.354906,510.612650,112.070936,218.790677,290.161462,1.612037,11172.387369,5230.047117,16103.907238,156.409514,...,1780.821420,0.000000,5907.567510,620.943143,2309.696444,327.612895,297.575140,3838.591796,1655.732370,57.070395
2,2023,436.234488,389.286763,75.969461,157.123145,184.449193,0.947411,7704.226091,3114.103031,11379.178223,115.821127,...,1181.354928,0.000000,4671.554618,645.638747,1839.012931,243.180386,237.366306,3206.183538,857.304202,36.363988